// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class BatteryType
{
    public Guid BatteryTypeId { get; set; }

    public string TypeCode { get; set; }

    public string TypeName { get; set; }

    public string Manufacturer { get; set; }

    public decimal CapacityKwh { get; set; }

    public decimal? Voltage { get; set; }

    public decimal? WeightKg { get; set; }

    public string Dimensions { get; set; }

    public int? WarrantyCycles { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();
}