// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class Driver
{
    public Guid DriverId { get; set; }

    public Guid UserId { get; set; }

    public string DriverLicense { get; set; }

    public Guid? SubscriptionPlanId { get; set; }

    public string SubscriptionStatus { get; set; }

    public DateOnly? SubscriptionStartDate { get; set; }

    public DateOnly? SubscriptionEndDate { get; set; }

    public int TotalSwaps { get; set; }

    public int LoyaltyPoints { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}