// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class ev_battery_swapContext : DbContext
{
    public ev_battery_swapContext(DbContextOptions<ev_battery_swapContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Battery> Batteries { get; set; }

    public virtual DbSet<BatteryType> BatteryTypes { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<VehicleModel> VehicleModels { get; set; }
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Battery>(entity =>
        {
            entity.HasKey(e => e.BatteryId).HasName("pk_batteries");

            entity.ToTable("batteries");

            entity.HasIndex(e => e.BatteryTypeId, "ix_batteries_battery_type");

            entity.HasIndex(e => e.ChargeLevel, "ix_batteries_charge_level");

            entity.HasIndex(e => e.SohPercentage, "ix_batteries_soh");

            entity.HasIndex(e => e.StationId, "ix_batteries_station");

            entity.HasIndex(e => e.Status, "ix_batteries_status");

            entity.HasIndex(e => e.BatteryCode, "ux_batteries_code").IsUnique();

            entity.HasIndex(e => e.SerialNumber, "ux_batteries_serial").IsUnique();

            entity.Property(e => e.BatteryId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("battery_id");
            entity.Property(e => e.BatteryCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("battery_code");
            entity.Property(e => e.BatteryTypeId).HasColumnName("battery_type_id");
            entity.Property(e => e.ChargeLevel).HasColumnName("charge_level");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.LastMaintenanceDate).HasColumnName("last_maintenance_date");
            entity.Property(e => e.LastSwapDate).HasColumnName("last_swap_date");
            entity.Property(e => e.ManufactureDate).HasColumnName("manufacture_date");
            entity.Property(e => e.NextMaintenanceDate).HasColumnName("next_maintenance_date");
            entity.Property(e => e.PurchaseDate).HasColumnName("purchase_date");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("serial_number");
            entity.Property(e => e.SohPercentage)
                .HasDefaultValue(100.00m)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("soh_percentage");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("available")
                .HasColumnName("status");
            entity.Property(e => e.TotalCycles).HasColumnName("total_cycles");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.BatteryType).WithMany(p => p.Batteries)
                .HasForeignKey(d => d.BatteryTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_batteries_battery_types");

            entity.HasOne(d => d.Station).WithMany(p => p.Batteries)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_batteries_stations");
        });

        modelBuilder.Entity<BatteryType>(entity =>
        {
            entity.HasKey(e => e.BatteryTypeId).HasName("pk_battery_types");

            entity.ToTable("battery_types");

            entity.HasIndex(e => e.TypeCode, "ux_battery_types_code").IsUnique();

            entity.Property(e => e.BatteryTypeId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("battery_type_id");
            entity.Property(e => e.CapacityKwh)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("capacity_kwh");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Dimensions)
                .HasMaxLength(100)
                .HasColumnName("dimensions");
            entity.Property(e => e.Manufacturer)
                .HasMaxLength(100)
                .HasColumnName("manufacturer");
            entity.Property(e => e.TypeCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type_code");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("type_name");
            entity.Property(e => e.Voltage)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("voltage");
            entity.Property(e => e.WarrantyCycles).HasColumnName("warranty_cycles");
            entity.Property(e => e.WeightKg)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("weight_kg");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("pk_bookings");

            entity.ToTable("bookings");

            entity.HasIndex(e => e.DriverId, "ix_bookings_driver");

            entity.HasIndex(e => e.ScheduledTime, "ix_bookings_scheduled_time");

            entity.HasIndex(e => e.StationId, "ix_bookings_station");

            entity.HasIndex(e => e.Status, "ix_bookings_status");

            entity.Property(e => e.BookingId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("booking_id");
            entity.Property(e => e.BookingTime).HasColumnName("booking_time");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.ScheduledTime).HasColumnName("scheduled_time");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Driver).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("fk_bookings_drivers");

            entity.HasOne(d => d.Station).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_bookings_stations");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_bookings_vehicles");
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("pk_drivers");

            entity.ToTable("drivers");

            entity.HasIndex(e => e.UserId, "UQ__drivers__B9BE370EBF93FBE9").IsUnique();

            entity.HasIndex(e => new { e.SubscriptionPlanId, e.SubscriptionStatus }, "ix_drivers_subscription");

            entity.Property(e => e.DriverId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("driver_id");
            entity.Property(e => e.DriverLicense)
                .HasMaxLength(50)
                .HasColumnName("driver_license");
            entity.Property(e => e.LoyaltyPoints).HasColumnName("loyalty_points");
            entity.Property(e => e.SubscriptionEndDate).HasColumnName("subscription_end_date");
            entity.Property(e => e.SubscriptionPlanId).HasColumnName("subscription_plan_id");
            entity.Property(e => e.SubscriptionStartDate).HasColumnName("subscription_start_date");
            entity.Property(e => e.SubscriptionStatus)
                .HasMaxLength(20)
                .HasColumnName("subscription_status");
            entity.Property(e => e.TotalSwaps).HasColumnName("total_swaps");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("pk_stations");

            entity.ToTable("stations");

            entity.HasIndex(e => e.City, "ix_stations_city");

            entity.HasIndex(e => new { e.Latitude, e.Longitude }, "ix_stations_location");

            entity.HasIndex(e => e.Status, "ix_stations_status");

            entity.HasIndex(e => e.StationCode, "ux_stations_code").IsUnique();

            entity.Property(e => e.StationId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("station_id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasColumnName("address");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("city");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.District)
                .HasMaxLength(100)
                .HasColumnName("district");
            entity.Property(e => e.Is24Hours).HasColumnName("is_24_hours");
            entity.Property(e => e.Latitude)
                .HasColumnType("decimal(10, 8)")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasColumnType("decimal(11, 8)")
                .HasColumnName("longitude");
            entity.Property(e => e.ManagerId).HasColumnName("manager_id");
            entity.Property(e => e.OperatingHoursEnd)
                .HasDefaultValue(new TimeOnly(23, 59, 59))
                .HasColumnName("operating_hours_end");
            entity.Property(e => e.OperatingHoursStart).HasColumnName("operating_hours_start");
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("station_code");
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("station_name");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");
            entity.Property(e => e.TotalSlots).HasColumnName("total_slots");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("pk_vehicles");

            entity.ToTable("vehicles");

            entity.HasIndex(e => e.DriverId, "ix_vehicles_driver");

            entity.HasIndex(e => e.LicensePlate, "ux_vehicles_license_plate").IsUnique();

            entity.HasIndex(e => e.Vin, "ux_vehicles_vin").IsUnique();

            entity.Property(e => e.VehicleId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("vehicle_id");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .HasColumnName("color");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.LicensePlate)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("license_plate");
            entity.Property(e => e.ModelId).HasColumnName("model_id");
            entity.Property(e => e.RegistrationDate).HasColumnName("registration_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
            entity.Property(e => e.Vin)
                .IsRequired()
                .HasMaxLength(17)
                .HasColumnName("vin");

            entity.HasOne(d => d.Driver).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("fk_vehicles_drivers");

            entity.HasOne(d => d.Model).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.ModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_vehicles_models");
        });

        modelBuilder.Entity<VehicleModel>(entity =>
        {
            entity.HasKey(e => e.ModelId).HasName("pk_vehicle_models");

            entity.ToTable("vehicle_models");

            entity.HasIndex(e => e.BatteryTypeId, "ix_vehicle_models_battery_type");

            entity.HasIndex(e => e.Manufacturer, "ix_vehicle_models_manufacturer");

            entity.Property(e => e.ModelId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("model_id");
            entity.Property(e => e.BatteryTypeId).HasColumnName("battery_type_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Manufacturer)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("manufacturer");
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("model_name");
            entity.Property(e => e.ModelYear).HasColumnName("model_year");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}