// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class Station
{
    public Guid StationId { get; set; }

    public string StationCode { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public int TotalSlots { get; set; }

    public TimeOnly OperatingHoursStart { get; set; }

    public TimeOnly OperatingHoursEnd { get; set; }

    public bool Is24Hours { get; set; }

    public string Status { get; set; }

    public Guid? ManagerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}