// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class VehicleModel
{
    public Guid ModelId { get; set; }

    public string Manufacturer { get; set; }

    public string ModelName { get; set; }

    public int? ModelYear { get; set; }

    public Guid BatteryTypeId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}