// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingService.Domain.Models;

public partial class Vehicle
{
    public Guid VehicleId { get; set; }

    public Guid DriverId { get; set; }

    public string Vin { get; set; }

    public Guid ModelId { get; set; }

    public string LicensePlate { get; set; }

    public string Color { get; set; }

    public DateOnly? RegistrationDate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual VehicleModel Model { get; set; }
}